[package]
name    = "utils"
version = "0.1.0"
authors = ["Alex Burka <aburka@seas.upenn.edu>"]

[dependencies]
lazy_static = "0.2"
hprof  = "0.1"
notify = "4.0"
time = "0.1"
libc = "0.2"
errno = "0.2"

